### ISSUE TITLE
./lilac: symbol lookup error: ./lilac: undefined symbol: CBS_init

### ISSUE THREAD

**Issue by blitzbrian** [MercuryWorkshop/lilac#3]
When i try to patch my policy i get this error:
`./lilac: symbol lookup error: ./lilac: undefined symbol: CBS_init`

**Comment by r58Playz** [comment]
You need to export LD_LIBRARY_PATH to the boringssl library folder. This is in the blog post instructions, but not in the README. I'll fix it now.
